### ISSUE TITLE
reg data I/O

### ISSUE THREAD

**Issue by bindubhanu** [frankkramer-lab/MIScnn#12]
we have to store our dataset with imaging.nii.gz and the mask as segmentation.nii.gz?

**Comment by muellerdo** [comment]
Hey  bindubhanu,

if you want to use the provided NIfTI I/O interface for data loading, then yes. 
For using this interface, the following file structure is required:
```
sample_01/imaging.nii.gz
         /segmentation.nii.gz
sample_02/imaging.nii.gz
         /segmentation.nii.gz
sample_03/imaging.nii.gz
         /segmentation.nii.gz
...
sample_n/imaging.nii.gz
        /segmentation.nii.gz
```

But you can also implement a custom I/O interface for your own file structure or file formats using the Abstract Base Class for I/O interfaces as presented in the wiki.

I hope that I was able to help you :)

Cheers,
Dominik
