### ISSUE TITLE
PNG / NPY IO

### ISSUE THREAD

**Issue by asmagen** [frankkramer-lab/MIScnn#13]
Hello @muellerdo,

How do I perform multi class semantic (instance) segmentation over my set of 2D PNG/TIF grayscale images and their corresponding masks file (NPY numpy array, TIF or any other) matrix representation with # channels corresponding to the classes?
Do I need to use NIFTI_interface? If so, how do I convert my PNG/TIF/NPY files to this format?

Thank you

**Comment by muellerdo** [comment]
Hey @asmagen,

after multiple people asked me how setup a 2D medical image segmentation pipeline, I implemented an image IO interface for intuitive and easier integration of 2D image formats into MIScnn.

You have always the possibility to implement a custom data IO interface for your own file structure, but now you can also use the Image_interface class with a given fixed file structure.

I added an documented example of using the Image_interface on the ISBI cell tracking challenge 2015. 
https://github.com/frankkramer-lab/MIScnn/blob/master/examples/CellTracking.ipynb

> matrix representation with # channels corresponding to the classes
The number of channels is defined by your imaging data. Grayscale has 1 channel whereas RGB has 3 channels. 

I hope that I was able to help you.
If you have further questions don't hesitate to ask.

Cheers,
Dominik

PS:
Copy & Paste? :P
https://github.com/black0017/MedicalZooPytorch/issues/5
https://github.com/Project-MONAI/MONAI/issues/471

**Comment by asmagen** [comment]
Thank you. Regarding more project info and questions, I thought you might have an insight to suggest for my post [here](https://github.com/qubvel/segmentation_models/issues/350#issuecomment-640132569).

**Comment by muellerdo** [comment]
I'm sorry to say that due to time limiting issues currently, I am unable to provide support for non-related MIScnn questions.

But segmentation_models is a remarkable and popular package, so I'm optimistic that you will find good support there! :)
