### ISSUE TITLE
Multi-modal image segmentation

### ISSUE THREAD

**Issue by TerryShen7** [frankkramer-lab/MIScnn#16]
Hello Dr. Mueller,

I want to use both CT and MRI(multi-modal image) as input to the neural network for segmentation. 
Is there a chance to use your implementation so it will be suitable to my needs?

Best regards, 
Terry

**Comment by MichaelLempart** [comment]
Hi Terry,

have you tried to stack the CT and MR images into different image channels before using MIScnn?

Regards,

Michael

**Comment by muellerdo** [comment]
Hey TerryShen7,

> I want to use both CT and MRI(multi-modal image) as input to the neural network for segmentation.
Is there a chance to use your implementation so it will be suitable to my needs?

Sure, I'm quite optimistic that we can setup a medical image segmentation for your needs.

There are two approaches which pop up in my mind:

1. Training a single model with all modalities:
This approach is based on image registration and, then, combining all volumes into a single matrix with multiple channels. A pipeline with this approach, can be quite easily setup via MIScnn and channel specification as @MichaelLempart correctly suggested.

2. Building a cascade pipeline:
This approach is based on building separated models for each modality. Afterwards, the predictions of each model are interpolated by e.g. simply averaging or by another neural network model.

The more intuitive and more straightforward approach is training a single model. But cascade pipelines are becoming quite popular, in the last years.

Here is some literature for the cascade approach:
```
@article{Hou,
author = {Hou, Xiaoshuai and Xie, Chunmei and Li, F and Nan, Yang},
keywords = {automated detection and segmentation,ct,semantic,u-net},
pages = {2--6},
title = {{Cascaded Semantic Segmentation for Kidney and Tumor}}
}
@article{Valverde2017,
doi = {10.1016/j.neuroimage.2017.04.034},
issn = {10959572},
journal = {NeuroImage},
keywords = {Automatic lesion segmentation,Brain,Convolutional neural networks,MRI,Multiple sclerosis},
pages = {159--168},
publisher = {Elsevier},
title = {{Improving automated multiple sclerosis lesion segmentation with a cascaded 3D convolutional neural network approach}},
url = {http://dx.doi.org/10.1016/j.neuroimage.2017.04.034},
volume = {155},
year = {2017}
}
@article{Wang2018,
archivePrefix = {arXiv},
arxivId = {arXiv:1709.00382v2},
author = {Wang, Guotai and Li, Wenqi and Ourselin, S{\'{e}}bastien and Vercauteren, Tom},
doi = {10.1007/978-3-319-75238-9_16},
eprint = {arXiv:1709.00382v2},
isbn = {9783319752372},
issn = {16113349},
journal = {Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)},
keywords = {Brain tumor,Convolutional neural network,Segmentation},
pages = {178--190},
title = {{Automatic brain tumor segmentation using cascaded anisotropic convolutional neural networks}},
volume = {10670 LNCS},
year = {2018}
}
```

Hope that I was able to help you.

Cheers,
Dominik

**Comment by muellerdo** [comment]
I will close this issue due to inactivity.

If this issue was not solved, yet, feel free to open it up, agian! :)
