### ISSUE TITLE
Have no images in folder fold_0 and after running the C_drive gets full

### ISSUE THREAD

**Issue by ZeeshanAbbas92** [frankkramer-lab/MIScnn#24]
There were some folders which didn't have this "segmentation.nii.gz" file
so I deleted them and the error ended but now the problem is when I run
this it takes too much memory and it naked the C-drive full i.e. 100GB.
What is the reason?

Second thing:
"from IPython.display import Image
Image(filename = "evaluation/fold_0/validation.dice_soft.png")"

I don't have any images in this folder fold_0. How can I resolve
these issues?

Best Regards,

**Comment by muellerdo** [comment]
Hey @ZeeshanAbbas92,

can you specify "too much memory"?
The standard 3D U-Net for a patch shape of around 128x128x128 with batch normalization requires around 16GB VRAM. Without 8GB VRAM.
Which GPU are you using? Maybe, I'm optimistic that we can tweak the configuration that you get a powerful model.

> @ZeeshanAbbas92 said:
 > it naked the C-drive full i.e. 100GB

The size of your temporary batch directory should be around the same size as your data set.
I'm guessing you are referring to the KiTS19 example, am I correct?
If yes, then your batch directory should be take around 25GB disk space.
If the size is higher, I would guess that some old temporary files were not correctly deleted. This can occur if MIScnn was not successfully finished through e.g. errors.

> @ZeeshanAbbas92 said:
>I don't have any images in this folder fold_0. How can I resolve
these issues?

This is quite strange if you successfully reproduced the Jupyter Notebook example.
Could you post your console log of the reproduction?

Cheers,
Dominik

**Comment by muellerdo** [comment]
I will close this issue due to inactivity.

If this issue was not solved, yet, please do not hesitate to open it up, again.
