### ISSUE TITLE
Could I run this project based on Tensorflow-gpu == 1.14.0

### ISSUE THREAD

**Issue by Iamyourbaba** [frankkramer-lab/MIScnn#33]

**Comment by muellerdo** [comment]
Hey @Iamyourbaba,

yes, you can use an outdated version of MIScnn for Tensorflow 1.14.

Check out the TF1.14 branch on the Github: https://github.com/frankkramer-lab/MIScnn/tree/TF-1.14
Or just download the MIScnn-TF-1.14 version on PyPI: https://pypi.org/project/miscnn-TF-1.14/

But be aware that the MIScnn TF 1.14 version is fixed on MIScnn version 0.32 and is deprecated. It could contain old and already fixed bugs.

Cheers,
Dominik Müller
