### ISSUE TITLE
Custom architecture

### ISSUE THREAD

**Issue by covasquezv** [frankkramer-lab/MIScnn#38]
Hi! according to the documentation it is possible to use a custom architecture using an abstract class. 
Since it is briefly mentioned and there's not much information about it, I would like to know if there's any tutorial/example to understand how to use it. I haven't been able to get it with what's currently available.

Thanks in advance!

**Comment by muellerdo** [comment]
Hey @covasquezv,

you are right. Sadly, there was not much documentation on custom architectures.

Therefore, I wrote a little tutorial Jupyter Notebook on how to integrate custom architectures into the MIScnn pipeline  
and also updated the architecture page in the Wiki.

Check out this: https://github.com/frankkramer-lab/MIScnn/blob/master/tutorials/Custom_Architecture.ipynb

Hope that this will help you in your further research with MIScnn.

Cheers,
Dominik

**Comment by covasquezv** [comment]
Great! The tutorial is very clear for me.
Thanks a lot!

Best,
Constanza
