### ISSUE TITLE
Weight initialization 

### ISSUE THREAD

**Issue by shanpriya3** [frankkramer-lab/MIScnn#4]
Hi, can I use different weight initialization eg: xavier/ glorot method? To do so, can I just define it in def_init(... initialization= glorot_normal,...) in model.py?

**Comment by muellerdo** [comment]
Heyho shanpriya3,

as far as I know, Tensorflow/Keras doesn't support a global change in default weight initialization.  
ref: https://github.com/tensorflow/tensorflow/issues/26282

Normally, you have to define the default weight initialization for each layer of your model. Therefore, the first possibility would be to modify your desired architecture and just add the kernel_initializer tag to every layer:
```python
model.add(Dense(64, kernel_initializer='glorot_normal'))
```

Another possibility would be to change the weights after the architecture initialization. You can access the Keras model of the MIScnn pipeline with the following code:
```python
miscnn_model = Neural_Network(preprocessor=pp)
keras_model = miscnn_model.model
```
Then you can iterate over the layers of the Keras model and manually assign the weights to each layer without changing the source code of the architecture.
```python
import numpy as np
for layer in keras_model.layers:
     shape = layer.get_weights().shape
     weights = np.zeroes(shape) # todo: call glorot function
     layer.set_weights(weights)
```
Here are some more refs for weight initialization in Keras: 
https://keras.io/layers/about-keras-layers/  
https://keras.io/initializers/  
https://stackoverflow.com/questions/54009036/how-to-extract-weights-from-input-layer-to-hidden-layer-and-from-hidden-layer/54009163#54009163

Greetings,
Dominik
