### ISSUE TITLE
3D image sliced in 2D Patches

### ISSUE THREAD

**Issue by Artia5000** [frankkramer-lab/MIScnn#8]
When trying to implement a 2D network from 3D volumes with patchgrid approach i encountered several errors in mismatch of dimensions, the framework configures the nets on the dimensions of the sample imaging source, not on the final patch size. To overcome i had forced a couple of sections to 2d mode and added some lines to squeeze out one axis in patch generation and to add one in patch concat, but i think this can be a nice feature to have structured in the framework

**Comment by muellerdo** [comment]
Hey Artia5000,

sorry for the late response.

You are right, this isn't implemented in MIScnn, yet.
But it should be! 
Running 2D networks on slices of 3D volumes is still a common approach in medical image analysis and could be a quite handy feature in MIScnn.

I'm adding it to the MIScnn agenda/to-do list. :)
Thanks for sharing your experiences and contributing feedback for MIScnn!

Also I'm always interested in projects using MIScnn, so if you want to share your project/code as an usage example, you are more than welcome :)

Cheers,
Dominik

**Comment by Artia5000** [comment]
Dear Dominik,
at the moment i am working on white matter hyperintensities segmentation. If i'll be able to produce some shareable results i will be glad to contribute to this very nice framework!

Lorenzo

**Comment by muellerdo** [comment]
#### Update:
I implemented a NIfTI slicer IO Interface, which takes 3D volumes and slices them automatically into 2D.  
Now, you can just add the new IO Interface to your MIScnn pipeline and work with 2D architectures on a 3D data set.  
Afterwards, predictions will be saved as NumPy pickles.

I tested it on the KiTS19 data set which consists of 3D CT volumes.  
Any other feedback or testing is, as always, welcome and encouraged. :)

Cheers,
Dominik
